name: my_first_flutter_project
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  charts_flutter: ^0.6.0
  font_awesome_flutter: ^8.2.0
  shared_preferences: ^ 0.4.2 
  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  fl_chart: ^0.9.3
  pdf: ^1.5.0
  path_provider: ^1.6.5
  flutter_full_pdf_viewer: ^1.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^1.3.3


flutter:
  uses-material-design: true
  
  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/cm_sans_serif_2012.ttf
   - assets/fonts/a_BighausTitul.ttf
   - assets/fonts/first.ttf
   - assets/fonts/second.ttf

  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf
   - family: Ramon
     fonts:
       - asset: assets/fonts/a_BighausTitul.ttf
   - family: Ramon
     fonts:
       - asset: assets/fonts/second.ttf
  
  